Repository ucsb-cs156-f24/proj-courses-f24-02, pull requests merged in 2024-11, with the labels that each got.

#12 Prevent making Personal Schedules in same quarter with duplicate names through edit
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesEditPage.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesEditPage.test.js
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesControllerTests.java
Labels: Merge Candidate-Dokku

#16 Added Clear Job Logs button to AdminJobsPage
  frontend/src/main/components/Jobs/ClearJobsForm.js
  frontend/src/main/pages/Admin/AdminJobsPage.js
  frontend/src/tests/components/Jobs/ClearJobsForm.test.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: 10

#15 made descriptions optional
  frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleForm.test.js
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
Labels: 5

#17 Added getActiveQuarters method to UCSBAPIQuarterService and /api/public/activeQuarters endpoint
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBAPIQuarterController.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBAPIQuarterService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBAPIQuarterControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBAPIQuarterServiceTests.java
Labels: 10, Merge Candidate-CI

#27 Created Placeholder Page for Updates, Accessible Only by Admin(s)
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Admin/AdminUpdatesPage.js
  frontend/src/stories/pages/Admin/AdminUpdatesPage.stories.js
  frontend/src/tests/pages/AdminUpdatesPage.test.js
Labels: 5, Merge Candidate-CI

#28 Added SingleButtonJobForm component
  frontend/src/main/components/Jobs/SingleButtonJobForm.js
  frontend/src/main/components/Jobs/UpdateGradeInfoForm.js
  frontend/src/main/pages/Admin/AdminJobsPage.js
  frontend/src/stories/components/Jobs/SingleButtonJobForm.stories.js
  frontend/src/tests/components/Jobs/ClearJobsForm.test.js
  frontend/src/tests/components/Jobs/SingleButtonJobForm.test.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: 10, Merge Candidate-CI

#31 UpdatesTable implemented, All Tests Passing and Storybook Setup
  frontend/src/fixtures/updatesFixtures.js
  frontend/src/main/components/Updates/UpdatesTable.js
  frontend/src/stories/components/Updates/UpdatesTable.stories.js
  frontend/src/tests/components/Updates/UpdatesTable.test.js
Labels: 10, Merge Candidate-CI

#18 Added Helpful Error Message When User Adds Two Sections of the Same Course to Schedule
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
  src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java
Labels: 10, Merge Candidate-CI

#34 Modified SingleQuarterDropdown and SingleSubjectDropdown to have "ALL" Option
  frontend/src/main/components/Quarters/SingleQuarterDropdown.js
  frontend/src/main/components/Subjects/SingleSubjectDropdown.js
  frontend/src/stories/components/Quarters/SingleQuarterDropdown.stories.js
  frontend/src/stories/components/Subjects/SingleSubjectDropdown.stories.js
  frontend/src/tests/components/Quarters/SingleQuarterDropdown.test.js
  frontend/src/tests/components/Subjects/SingleSubjectDropdown.test.js
Labels: 10, Merge Candidate-CI

#22 Get job by ID added to controller file
  src/main/java/edu/ucsb/cs156/courses/controllers/JobsController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/JobsControllerTests.java
Labels: 10, Merge Candidate-CI

#30 Reduced clutter in log from course update jobs
  src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataJob.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataJobTests.java
Labels: 5, Ready-For-Staff, Merge Candidate-CI
